import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { Suspense } from "react";
import NavbarServer from "./components/common/NavbarServer";
import NavbarSkeleton from "./components/common/NavbarSkeleton";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "GearUp",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
        >
            <body className="min-h-full flex flex-col">
                <Toaster position='top-right' richColors />
                <header>
                    <Suspense fallback={<NavbarSkeleton />}>
                        <NavbarServer />
                    </Suspense>
                </header>

                <main>
                    {children}
                </main>
            </body>
        </html >
    );
}
